services:
  # Service 1: Web Server (Apache + PHP)
  web:
    build:
      context: .
      dockerfile: .docker/php/dockerfile
    container_name: ruanginPNJ_server
    ports:
      - "8082:80" # Akses project dari http://localhost:8082 di browser
    volumes:
      - .:/var/www/html # Mapping folder 'public' kita ke web root Apache
    depends_on:
      - db # Pastikan 'db' nyala dulu sebelum 'web'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Jakarta
    labels:
      ofelia.enabled: "true"
      # Nama job bebas, tetapi harus berbeda pada setiap job
      # "@every 5m" artinya dijalankan setiap 5 menit
      ofelia.job-exec.cancel-job.schedule: "@every 2m"
      ofelia.job-exec.cancel-job.command: "php /var/www/html/cli.php bookings:autocancel"
      # ini akan berjalan setiap 5 menit untuk mengecek apakah ada booking yang sudah selesai tapi statusnya belum berubah
      ofelia.job-exec.complete-job.schedule: "@every 2m"
      ofelia.job-exec.complete-job.command: "php /var/www/html/cli.php bookings:autocomplete"
      # ini untuk otomasi reminder
      ofelia.job-exec.reminder-start.schedule: "@every 2m"
      ofelia.job-exec.reminder-start.command: "php /var/www/html/cli.php reminders:start"
      ofelia.job-exec.reminder-end.schedule: "@every 2m"
      ofelia.job-exec.reminder-end.command: "php /var/www/html/cli.php reminders:end"

  # Service 2: Database (MySQL)
  db:
    image: mysql:8.0
    container_name: ruanginPNJ_database
    command: --log-bin-trust-function-creators=1
    ports:
      - "3307:3306" # Opsional: jika Anda ingin akses DB dari luar (mis: DBeaver)
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Menyimpan data database secara permanen

  mailpit:
    image: axllent/mailpit
    container_name: ruanginPNJ_mail
    ports:
      - "8025:8025" # Ini adalah port untuk Web UI Mailpit
      - "1025:1025" # Ini adalah port SMTP (internal)
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true # Menerima login apapun
      - MP_SMTP_AUTH_ALLOW_INSECURE=true # Izinkan koneksi tanpa enkripsi

  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ruanginPNJ_scheduler
    environment:
      - TZ=Asia/Jakarta
    depends_on:
      - web
    command: daemon --docker
    volumes:
      # Ofelia butuh akses ke docker socket untuk bisa mengontrol container lain
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  db_data: # volume untuk data database agar permanen
