# 1. Mulai dari image PHP + Apache
FROM php:8.2-apache

# 2. Install dependensi sistem untuk Composer dan ekstensi PHP
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_mysql zip gd \
    && a2enmod rewrite \
    && rm -rf /var/lib/apt/lists/*

#Install Composer resmi dari image composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

#Set working directory
WORKDIR /var/www/html

# Buat file composer.json dan install PHPMailer langsung
RUN composer require phpmailer/phpmailer
RUN composer require vlucas/phpdotenv

# salin file depedensi
COPY composer.json composer.lock ./
#langsung install aja kalo udah ada composer.json dan composer.lock
RUN composer install --no-interaction --no-scripts --optimize-autoloader

# 6. (Opsional) Salin kode aplikasi kamu
COPY . .

# 7. (Opsional) Set permission file
# RUN chown -R www-data:www-data /var/www/html
WORKDIR /var/www/html
RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf

# # Copy entrypoint script ke dalam container
# COPY .docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
# RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# ENTRYPOINT ["docker-entrypoint.sh"]
# CMD ["apache2-foreground"]
